FROM php:7.3-fpm

# cài đặt và kích hoạt opcache, mysqli, pdo_mysql, memcached

RUN apt-get update -y 
RUN apt-get install libzip-dev zip libmemcached-dev  -y  
RUN docker-php-ext-install zip opcache mysqli pdo_mysql 
RUN docker-php-ext-enable mysqli 
RUN docker-php-ext-enable opcache 
RUN docker-php-ext-enable pdo_mysql 
RUN pecl install memcached 
RUN rm -rf /var/lib/apt/lists/*


ADD ./php.ini /usr/local/etc/php/php.ini

EXPOSE 9000
