version: '2'

networks:
    LEMP:

services:
    nginx:
        image: nginx:latest
        container_name: LEMP_nginx
        ports:
            - "8282:80"
        volumes:
            - ./codephp:/usr/share/nginx/html
            - ./config_nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - LEMP

    mysql:
        image: mysql:version2
        container_name: LEMP_mysql
        volumes:
            - ./database:/var/lib/mysql:rw
        ports:
            - "4444:3306"
        depends_on:
            - nginx
        environment:
            - MYSQL_ROOT_PASSWORD=kuuhaku
        networks:
            - LEMP
    php:
        image: php:version1
        container_name: LEMP_php
        volumes:
            - ./codephp:/usr/share/nginx/html
        ports:
            - "9000:9000"
        networks:
            - LEMP

